### PR TITLE
Ability to have different config file names apart from tox.ini

### LINKED ISSUE #80: Allow use of setup.cfg
Enhancement request: it would be nice if we had the choice to use `setup.cfg` on top of `tox.ini`.

### PR DESCRIPTION
**Pull request by nanorepublica**
Currently I only added support for setup.cfg as well

Fixes #80.

Please let me know if you want me to add anymore in terms of testing.

### CODE REVIEW

**Comment by nanorepublica** [comment]
Just updated the readme to reflect the option of the 2 files

**Comment by alexcouper** [comment]
Thanks for the PR :)

Could you rebase from master so that this is mergable?

**Comment by nanorepublica** [comment]
rebased to 1 commit, looks all good to me now :)

**Comment by alexcouper** [comment]
Looking good.

I'll play with this soon (might be next week) before merging and releasing.

**Comment by alexcouper** [comment]
Works well. :+1:

**Pull request merged**
