### PR TITLE
#77 Make sure .git/hooks exists before installing

### PR DESCRIPTION
**Pull request by browniebroke**
Way of fixing the error I had in #77

### CODE REVIEW

**Comment by alexcouper** [comment]
Thanks - another approach would be to use ``os.makedirs`` here https://github.com/alexcouper/captainhook/blob/master/scripts/captainhook#L65

I think I prefer that approach.

**Comment by browniebroke** [comment]
That was my first approach, but the install_pre_commit_hook fails too (see
logs in the issue)

**Comment by alexcouper** [comment]
Ah yes - fair point.

I'll give this a spin then

**Comment by alexcouper** [comment]
Works like a charm. Merging.

Thanks

**Pull request merged**
